title: p:paf
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
 
baseurl: "Atharva_Template" # the subpath of your site, e.g. /blog
url: "https://atharva-chandak.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

theme: minima
plugins:
  - jekyll-feed
